name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, 'skip') && contains(github.event.head_commit.message, 'ci'))"
    steps:
      - name: Prepare
        run: ''

  build:
    runs-on: macos-latest
    needs: [prepare]
    steps:
    - uses: actions/checkout@v2

    - name: Find solution
      id: find-solution
      run: |
        path=$(find ** -name '*.sln' -type f | head -1)
        echo "::set-output name=path::$path"

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Restore dependencies
      run: msbuild ${{ steps.find-solution.outputs.path }} /t:restore

    - name: Build
      run: msbuild ${{ steps.find-solution.outputs.path }} /t:build

    - name: Restore dotnet tools
      run: dotnet tool restore

    - name: Find test dll
      id: find-test-dll
      run: |
        path=$(find **/bin/ -name '*Tests.dll' -type f | head -1)
        echo "::set-output name=path::$path"

    - name: Test
      run: dotnet xunit ${{ steps.find-test-dll.outputs.path }} -stoponfail

    - name: Format
      run: dotnet dotnet-format --check
